start_conversation_data = [
    ("Hi, can we start a conversation?", "start_convo"),
    ("Let's chat. Can we begin?", "start_convo"),
    ("Hello, I'm here. Let's talk.", "start_convo"),
    ("Is this a good time to start a conversation?", "start_convo"),
    ("I'd like to initiate a discussion.", "start_convo"),
    ("Can we have a chat now?", "start_convo"),
    ("Starting a conversation with you.", "start_convo"),
    ("I want to begin a conversation.", "start_convo"),
    ("Let's get this conversation started.", "start_convo"),
    ("Is this the right place to talk?", "start_convo"),
    ("I'm ready for a conversation.", "start_convo"),
    ("Ready for a discussion.", "start_convo"),
    ("Starting a new chat.", "start_convo"),
    ("We should have a conversation.", "start_convo"),
    ("Starting a conversation now.", "start_convo"),
    ("I'd like to talk, please.", "start_convo"),
    ("Can we begin a conversation?", "start_convo"),
    ("I'm here for a chat.", "start_convo"),
    ("Initiating a conversation with you.", "start_convo"),
    ("Let's start our discussion.", "start_convo")
]

show_fields_data = [
    ("Please show me the available fields.", "show_fields"),
    ("I need to see the list of fields.", "show_fields"),
    ("Can you display the fields for me?", "show_fields"),
    ("Show me the data fields.", "show_fields"),
    ("I'd like to view the fields.", "show_fields"),
    ("Display the available data fields.", "show_fields"),
    ("I want to see the list of fields.", "show_fields"),
    ("Show the fields, please.", "show_fields"),
    ("Can you show me the data categories?", "show_fields"),
    ("I need to access the fields.", "show_fields"),
    ("Display the data fields on the screen.", "show_fields"),
    ("I'd like a list of the available fields.", "show_fields"),
    ("Please show the data categories.", "show_fields"),
    ("I'm interested in the fields.", "show_fields"),
    ("Can you present the data fields to me?", "show_fields"),
    ("I want to examine the data categories.", "show_fields"),
    ("Show me the available data fields.", "show_fields"),
    ("I'd like to check out the fields.", "show_fields"),
    ("Please display the fields.", "show_fields"),
    ("Show me the list of fields, please.", "show_fields")
]

retry_basic_fetch_data = [
    ("I didn't get the stock information. Can you try again?", "retry_basic_fetch"),
    ("The stock data didn't load. Retry, please.", "retry_basic_fetch"),
    ("Please fetch the stock details once more.", "retry_basic_fetch"),
    ("Can you attempt to fetch the stock data again?", "retry_basic_fetch"),
    ("I still need the stock information. Retry, please.", "retry_basic_fetch"),
    ("The stock details are missing. Retry the retrieval.", "retry_basic_fetch"),
    ("I couldn't access the stock data. Please retry.", "retry_basic_fetch"),
    ("The stock information didn't load. Try again, please.", "retry_basic_fetch"),
    ("I didn't receive the stock details. Please retry.", "retry_basic_fetch"),
    ("The stock data didn't load correctly. Retry, please.", "retry_basic_fetch"),
    ("Can you fetch the stock information again?", "retry_basic_fetch"),
    ("The stock details didn't come through. Retry.", "retry_basic_fetch"),
    ("I'm missing the stock information. Retry, please.", "retry_basic_fetch"),
    ("The stock data retrieval failed. Retry, please.", "retry_basic_fetch"),
    ("Can you try fetching the stock details again?", "retry_basic_fetch"),
    ("The stock information is missing. Retry, please.", "retry_basic_fetch"),
    ("The stock data retrieval wasn't successful. Retry.", "retry_basic_fetch"),
    ("I need the stock details. Please retry the retrieval.", "retry_basic_fetch"),
    ("The stock data didn't come through. Retry, please.", "retry_basic_fetch"),
    ("Can you try to fetch the stock information again?", "retry_basic_fetch")
]

old_reports_data = [
    ("Can you show me my previous reports?", "old_reports"),
    ("I'd like to see a list of my old reports.", "old_reports"),
    ("Retrieve my past generated reports, please.", "old_reports"),
    ("Can you provide me with a history of my reports?", "old_reports"),
    ("I want to access my previous report documents.", "old_reports"),
    ("List all the reports I've generated in the past.", "old_reports"),
    ("Show me the reports I've created before.", "old_reports"),
    ("I need to view my historical reports.", "old_reports"),
    ("Retrieve a list of my old report files.", "old_reports"),
    ("Can you display my previous report documents?", "old_reports"),
    ("I'd like to check my report history.", "old_reports"),
    ("Show me my previously generated reports, please.", "old_reports"),
    ("I want a list of reports I've generated in the past.", "old_reports"),
    ("Retrieve my historical reports for review.", "old_reports"),
    ("Can you provide a summary of my old reports?", "old_reports"),
    ("I'd like to access my previous report files.", "old_reports"),
    ("Show me a record of reports I've created.", "old_reports"),
    ("I need to view my reports from the past.", "old_reports"),
    ("Retrieve my old report data for reference.", "old_reports"),
    ("Can you list all my previously generated reports?", "old_reports")
]

generate_new_report_data = [
    ("I'd like to generate a new report.", "generate_new_report"),
    ("Generate a new report for me, please.", "generate_new_report"),
    ("Please create a new report.", "generate_new_report"),
    ("I want to generate a report.", "generate_new_report"),
    ("Generate a report.", "generate_new_report"),
    ("Create a new report.", "generate_new_report"),
    ("Generate a fresh report.", "generate_new_report"),
    ("I need a new report.", "generate_new_report"),
    ("Create a report.", "generate_new_report"),
    ("I'd like a report.", "generate_new_report"),
    ("Generate a report document.", "generate_new_report"),
    ("Create a new report file.", "generate_new_report"),
    ("Generate a report for me.", "generate_new_report"),
    ("I want a new report.", "generate_new_report"),
    ("Generate a report, please.", "generate_new_report"),
    ("Create a report file.", "generate_new_report"),
    ("Generate a new document.", "generate_new_report"),
    ("I need a report generated.", "generate_new_report"),
    ("Create a report for me.", "generate_new_report"),
    ("Generate a report file, please.", "generate_new_report")
]

fetch_basic_stocks_data = [
    ("Fetch basic stock information, please.", "fetch_basic_stocks"),
    ("I'd like to get basic stock details.", "fetch_basic_stocks"),
    ("Can you fetch me some stock data?", "fetch_basic_stocks"),
    ("I want to fetch basic stocks.", "fetch_basic_stocks"),
    ("Fetch me the stock information.", "fetch_basic_stocks"),
    ("Please provide basic stock data.", "fetch_basic_stocks"),
    ("I need to fetch basic stock information.", "fetch_basic_stocks"),
    ("Fetch basic stock details for me.", "fetch_basic_stocks"),
    ("Can you get me the stock data?", "fetch_basic_stocks"),
    ("I'd like to retrieve basic stock information.", "fetch_basic_stocks"),
    ("Fetch the basic stock data, please.", "fetch_basic_stocks"),
    ("I want to access basic stock details.", "fetch_basic_stocks"),
    ("Please fetch basic stock data.", "fetch_basic_stocks"),
    ("I need the basic stock information.", "fetch_basic_stocks"),
    ("Fetch the basic stocks, please.", "fetch_basic_stocks"),
    ("I'd like to fetch stock data.", "fetch_basic_stocks"),
    ("Can you retrieve basic stock details?", "fetch_basic_stocks"),
    ("I want to get basic stock data.", "fetch_basic_stocks"),
    ("Fetch the basic stock information.", "fetch_basic_stocks"),
    ("Please provide me with basic stock details.", "fetch_basic_stocks")
]